services:
  windows:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: windows
    environment:
      VERSION: "win11"
      USERNAME: "poespas"
    devices:
      - /dev/kvm
    volumes:
      - ./oem:/oem
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      # - 3389:3389/tcp
      # - 3389:3389/udp
    stop_grace_period: 2m
